[package]
name = "bcs"
version = "0.1.2"
description = "BCS (Binary Canonical Serialization) implementation for Motoko - Reference implementation compatible with SUI's BCS"
repository = "https://github.com/jneums/motoko-bcs"
keywords = ["bcs", "serialization", "sui", "move", "binary"]
license = "MIT"

[dependencies]
base = "0.16.0"

[toolchain]
moc = "0.16.0"